apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: ${K8S_NAMESPACE}
data:
  MYSQL_DATABASE: "appdb"
  MYSQL_USER: "appuser"

  my.cnf: |
    [mysqld]
    sql_mode=STRICT_ALL_TABLES
    max_connections=100
    innodb_buffer_pool_size=128M
