apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: ${K8S_NAMESPACE}
spec:
  resources:
    requests:
      storage: 1Gi
  # volumeMode: Filesystem
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
