####
# specifically for dev
# should not be push to git

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysql-secret
  namespace: ${K8S_NAMESPACE}
data:
  MYSQL_ROOT_PASSWORD: "myrootpass"
  MYSQL_PASSWORD: "mypass"
