apiVersion: v1
kind: Service
metadata: 
  name: ${SERVICE_NAME}
  namespace: ${K8S_NAMESPACE}
spec:
  type: ClusterIP
  selector:
    app: ${APP_NAME}
    color: blue
  ports:
    # - name: nginx-svc-port
    #   protocol: TCP
    - port: 80
      targetPort: 80