apiVersion: v1
kind: Service
metadata: 
  name: ${SERVICE_NAME}-blue
  namespace: ${K8S_NAMESPACE}
  labels:
    app: ${APP_NAME}
  annotationa:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  type: ClusterIP
  selector:
    app: ${APP_NAME}
    version: blue
  ports:
    - name: http
      port: 80
      targetPort: 80