apiVersion: v1
kind: Service
metadata: 
  name: web-service
  namespace: prod-app
spec:
  type: ClusterIP
  selector:
    app: web-app
  ports:
    # - name: nginx-svc-port
    #   protocol: TCP
    - port: 80
      targetPort: 80