apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_NAME}-configmap
  namespace: ${K8S_NAMESPACE}
data:
  APP_ENV: "prod"
  LOG_LEVEL: "warn"
  FEATURE_FLAGS: "enableSignup=true, enableCache=false"
