apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - blue-deployment.yaml
  - green-deployment.yaml
  - service-blue.yaml
  - service-green.yaml
  - ingress.yaml

# cluster wide labels
commonLabels:     
  app.kubernetes.io/name: web-name
  app.kubernetes.io/part-of: web-app